api_id = 1234567
api_hash = "344583e45741c457fe1862106095a5eb"
bot_token = "1234567890:AAHfiqksKZ8WmR2zSjiQ7_v4TMAKdiHm9T0"
username = "your_username"

database_uri = "sqlite://storage.db?mode=rwc"

listen_port = 8000
auth_access_key = "YOUR_ACCESS_KEY"
auth_secret_key = "YOUR_SECRET_KEY"
